language: node_js
sudo: required
node_js:
- '6'
before_install:
- echo -e "\n212.145.241.20 api3.tmb.cat" | sudo tee -a /etc/hosts
- echo "212.145.241.20 api1.tmb.cat" | sudo tee -a /etc/hosts
- echo "212.145.241.20 api2.tmb.cat" | sudo tee -a /etc/hosts
- echo "212.145.241.20 api3.tmb.cat" | sudo tee -a /etc/hosts
- openssl aes-256-cbc -K $encrypted_0e142905b713_key -iv $encrypted_0e142905b713_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
