language: node_js
node_js:
- '4'
before_install:
- openssl aes-256-cbc -K $encrypted_0e142905b713_key -iv $encrypted_0e142905b713_iv
  -in api_keys.json.enc -out api_keys.json -d
- sh -e /etc/init.d/xvfb start
